### ISSUE TITLE
Ping URL must be mandatory

### ISSUE THREAD

**Issue by flaviovs** [flaviovs/vault#1]
There's no point in having an app without a ping URL, because the app is responsible to notify engineers upon secret input, and it can only get to know this by being pinged by the Vault.

**Comment by mdawaffe** [comment]
This confused me :) I thought perhaps I could use the CLI as a full client for debugging.

**Comment by flaviovs** [comment]
This was my initial method of creating requests to debug the system, before the client app was ready to use. I agree that it is of limited use now, but still is a proper way to generate a request nevertheless!

For instance, to debug the tool I generally enable mailer debug in config.ini (so that emails are not sent, just logged), use the CLI to generate requests, and inspect logged emails for URLs and tokens. This save a few steps.

**Comment by mdawaffe** [comment]
> For instance, to debug the tool I generally enable mailer debug in config.ini (so that emails are not sent, just logged), use the CLI to generate requests, and inspect logged emails for URLs and tokens. This save a few steps.

Yeah - I did that.  I wasn't running a client, though, and I expected to be able to use the CLI to create the secret.

**Comment by flaviovs** [comment]
Oh, I see!

Surely, this is a good debug use case. I will try to implement it, because it might be really useful (and not that difficult do add). Will track this in #10 .
