### ISSUE TITLE
Merge client

### ISSUE THREAD

**Issue by flaviovs** [flaviovs/vault#17]
Now that the system is more mature, it became more and more clear that merging the client app might a be a good idea:
- Just 1 package, instead of 2
- More easy to understand the whole system
- Thus potentially easier to deploy
- No loss of decoupling -- clients still communicate with the engine through API

Steps:
- [x] Move app to `client/` folder
- [x] Move client-specific files in `lib/`
- [x] Check for common code
- [x] Update documentation

Cc @mdawaffe

**Comment by mdawaffe** [comment]
Now that the client exists in the same repo, should the config files be merged?

Also, is it possible to auto-generate the web client's keys so that it can be used straight away after running bin/install.php?

**Comment by flaviovs** [comment]
> Now that the client exists in the same repo, should the config files be merged?

Certainly they can be merged. But I am not sure if it is a good idea... My main concern is that mixing the settings will make the file confusing overall, without much gain (one file instead of two?). For example, the "client configuration" will contain a database connection section, even though it doesn't connect to a database. What do you think?

> Also, is it possible to auto-generate the web client's keys so that it can be used straight away after running bin/install.php?

Absolutely. But if I had to vote for it, I'm afraid I'd vote against it. :-) That's because during the install phase we are more concerned about setting up the infrastructure to the system run, while adding apps is more a model operation, so to speak. During install time we may not have the definitive ping url yet. We even might not be sure if we will be using the bundled client app (theoretically). But again, your feedback is welcome! :-)

**Comment by mdawaffe** [comment]
Why would the client configuration section contain database info?

As for auto-generating the client's keys, I suppose my real question is: is it valuable to separate out _this_ client at all? I see the utility of having an interface for other clients, but should the system ship with one that just works out of the box and can always be used if the integrator is having trouble with their own client?

This is all coming from the trouble I had setting up my own instance :) Another approach to minimizing that trouble would be to have better installation instructions. Could you look at the README again and make sure setting things up from scratch (a step by step process that would say how to set up the server and the client) is well documented?

**Comment by flaviovs** [comment]
> Why would the client configuration section contain database info?

I meant the the configuration file itself!

> As for auto-generating the client's keys, I suppose my real question is: is it valuable to separate out this client at all?(...)

I understand your point. More and more it makes sense to me too to make the two parts more integrated (or less separated, if you will). I think that a good README refactor could be a good step toward this. I will work on it.
