### ISSUE TITLE
Remove unused VaultClient::INSTRUCTIONS_ALLOWED_TAGS constant

### ISSUE THREAD

**Issue by flaviovs** [flaviovs/vault#23]

**Comment by mdawaffe** [comment]
`VaultClient::INSTRUCTIONS_ALLOWED_TAGS` is currently used in `Esc::instructions()` (though the escaping there isn't good enough, see #24).

**Comment by flaviovs** [comment]
Sure!

(Though the constant above is not being used -- the actual one is Request::INSTRUCTIONS_ALLOWED_TAGS.)
