### ISSUE TITLE
XSS when displaying instructions to user.

### ISSUE THREAD

**Issue by mdawaffe** [flaviovs/vault#24]
HEs can XSS users by including event attributes in the the instructions markup.

``` html
<b onmouseover=alert(1)>Hover over this</b>
```

This isn't problematic now, but it's unclear what tools in the future may accept user input to pre-generate instructions.

**Comment by flaviovs** [comment]
I always thought that XSS'ing users wasn't an issue (we're going to ask the user much more important info anyway), but the point you raised about other tools adding instruction is valid and important.
