### ISSUE TITLE
I can't create any secrets

### ISSUE THREAD

**Issue by mdawaffe** [flaviovs/vault#3]
https://github.com/flaviovs/vault/blob/5455673be8e1f7f19aa7bfe7eaac9b90a60f420f/lib/repo.php#L118-L126 is failing because `\DateTime::ISO8601` is not a valid datetime format according to MySQL.

> [CRITICAL] www: exception 'PDOException' with message 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2016-03-03T07:34:08+00:00'

The `+00:00` is what's breaking it for me.  Changing the format to `'Y-m-d H:i:s'` works for me.

What version of MySQL are you using?

**Comment by flaviovs** [comment]
I'm using Debian Jessie's package, which is 5.5.47-0+deb. But, yep, seems that the constant was not a good choice because [MySQL datetime literals officially does not support zone offsets](http://dev.mysql.com/doc/refman/5.7/en/date-and-time-literals.html).
