### ISSUE TITLE
`htmlspecialchars()` is a bit fragile without `ENT_QUOTES`

### ISSUE THREAD

**Issue by mdawaffe** [flaviovs/vault#5]
By default, `htmlspecialchars()` only encodes double quotes. The views in vault only use double quotes in attributes, so it's not currently a problem, but the code is fragile: some future change might introduce a single quote.

**Comment by flaviovs** [comment]
You are absolutely right. I postponed adding `esc_html()`/`esc_attr()`-like functions because the number of views is small, and I _never_ use single-quotes in attributes.
But of course, I may not be the only one maintaining this code in the future so, yes, it deserves a fix.

**Comment by mdawaffe** [comment]
> I may not be the only one maintaining this code in the future

Or your future self might not remember the rules :)

**Comment by flaviovs** [comment]
Thinking about other persons takes care of a possible unknown future self! :-)
